local M = {}
local p = require("pirokai_beach_sunset.palette")

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

local function set(groups, spec)
  for _, group in ipairs(groups) do
    hl(group, spec)
  end
end

function M.setup()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "pirokai-beach-sunset"

  hl("Normal", { fg = p.fg, bg = p.bg })
  hl("NormalNC", { fg = p.fg_dim, bg = p.bg })
  hl("NormalFloat", { fg = p.fg, bg = p.bg_float })
  hl("FloatBorder", { fg = p.border, bg = p.bg_float })
  hl("FloatTitle", { fg = p.yellow, bg = p.bg_float, bold = true })
  hl("Cursor", { fg = p.surface, bg = p.fg })
  hl("lCursor", { fg = p.surface, bg = p.fg })
  set({ "CursorLine", "CursorColumn" }, { bg = "#171717" })
  hl("ColorColumn", { bg = "#21161a" })
  hl("LineNr", { fg = p.muted, bg = p.bg })
  hl("CursorLineNr", { fg = p.fg_dim, bg = p.bg, bold = true })
  hl("SignColumn", { fg = p.muted, bg = p.bg })
  hl("FoldColumn", { fg = p.subtle, bg = p.bg })
  hl("Folded", { fg = p.comment, bg = p.bg_alt })
  set({ "VertSplit", "WinSeparator" }, { fg = p.border, bg = p.bg })
  hl("EndOfBuffer", { fg = p.bg, bg = p.bg })
  set({ "NonText", "Whitespace", "SpecialKey" }, { fg = p.muted })
  set({ "Visual", "VisualNOS" }, { bg = "#39373f" })
  hl("Search", { fg = p.surface, bg = p.yellow, bold = true })
  set({ "IncSearch", "CurSearch" }, { fg = p.surface, bg = p.orange, bold = true })
  hl("MatchParen", { fg = p.yellow, bg = p.surface, bold = true })
  hl("Directory", { fg = p.cyan })
  hl("Title", { fg = p.yellow, bold = true })
  set({ "Question", "MoreMsg" }, { fg = p.green })
  hl("ModeMsg", { fg = p.yellow, bold = true })
  hl("WarningMsg", { fg = p.orange })
  hl("ErrorMsg", { fg = p.red, bold = true })
  hl("MsgArea", { fg = p.fg, bg = p.bg })
  hl("Pmenu", { fg = p.fg_dim, bg = p.surface_alt })
  hl("PmenuSel", { fg = p.fg, bg = p.subtle, bold = true })
  hl("PmenuSbar", { bg = p.surface })
  hl("PmenuThumb", { bg = p.subtle })
  hl("WildMenu", { fg = p.surface, bg = p.yellow })
  hl("StatusLine", { fg = "#a8a8a8", bg = p.bg })
  hl("StatusLineNC", { fg = p.subtle, bg = p.bg_alt })
  hl("TabLine", { fg = p.comment, bg = p.bg })
  hl("TabLineSel", { fg = p.yellow, bg = p.bg, bold = true })
  hl("TabLineFill", { bg = p.bg })

  hl("Comment", { fg = p.comment, italic = true })
  set({ "Constant", "Number", "Boolean", "Float" }, { fg = p.purple })
  set({ "String", "Character" }, { fg = p.yellow })
  hl("Identifier", { fg = p.fg })
  hl("Function", { fg = p.green })
  set({ "Statement", "Conditional", "Repeat", "Operator", "Keyword", "Exception", "Include", "Define", "StorageClass" }, { fg = p.red })
  set({ "Label", "PreProc", "Macro", "PreCondit", "Special", "SpecialChar" }, { fg = p.orange })
  set({ "Type", "Structure", "Typedef" }, { fg = p.cyan })
  hl("Tag", { fg = p.red })
  hl("Delimiter", { fg = p.fg_dim })
  hl("SpecialComment", { fg = p.comment, italic = true })
  hl("Debug", { fg = p.red })
  hl("Underlined", { fg = p.cyan, underline = true })
  hl("Ignore", { fg = p.muted })
  hl("Error", { fg = p.red, bold = true })
  hl("Todo", { fg = p.surface, bg = p.yellow, bold = true })

  hl("@comment", { link = "Comment" })
  hl("@comment.documentation", { fg = p.comment, italic = true })
  hl("@comment.todo", { fg = p.surface, bg = p.yellow, bold = true })
  hl("@comment.note", { fg = p.surface, bg = p.cyan, bold = true })
  hl("@comment.warning", { fg = p.surface, bg = p.orange, bold = true })
  hl("@comment.error", { fg = p.surface, bg = p.red, bold = true })
  set({ "@constant", "@constant.builtin", "@number", "@boolean", "@float" }, { fg = p.purple })
  set({ "@string", "@string.documentation", "@character" }, { fg = p.yellow })
  set({ "@string.escape", "@constant.macro", "@function.macro", "@attribute", "@punctuation.special", "@tag.attribute" }, { fg = p.orange })
  hl("@string.regexp", { fg = p.cyan })
  hl("@variable", { fg = p.fg })
  hl("@variable.builtin", { fg = p.red, italic = true })
  set({ "@variable.parameter", "@variable.parameter.typescript", "@variable.parameter.tsx" }, { fg = p.parameter })
  set({ "@variable.member", "@property", "@field", "@label" }, { fg = p.orange })
  set({ "@module", "@type", "@type.definition" }, { fg = p.cyan })
  hl("@module.builtin", { fg = p.cyan, italic = true })
  set({ "@function", "@function.call", "@function.method", "@function.method.call", "@constructor" }, { fg = p.green })
  hl("@function.builtin", { fg = p.green, italic = true })
  set({ "@operator", "@keyword", "@keyword.coroutine", "@keyword.function", "@keyword.operator", "@keyword.import", "@keyword.type", "@keyword.modifier", "@keyword.repeat", "@keyword.return", "@keyword.debug", "@keyword.exception", "@keyword.conditional", "@type.qualifier", "@tag" }, { fg = p.red })
  hl("@keyword.directive", { fg = p.orange })
  hl("@type.builtin", { fg = p.cyan, italic = true })
  set({ "@punctuation.delimiter", "@punctuation.bracket", "@tag.delimiter" }, { fg = p.fg_dim })
  hl("@markup.heading", { fg = p.yellow, bold = true })
  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@markup.underline", { underline = true })
  set({ "@markup.link", "@markup.link.url" }, { fg = p.cyan, underline = true })
  hl("@markup.raw", { fg = p.yellow })
  hl("@markup.list", { fg = p.red })

  set({ "@lsp.type.class", "@lsp.type.enum", "@lsp.type.interface", "@lsp.type.namespace", "@lsp.type.struct", "@lsp.type.type" }, { fg = p.cyan })
  set({ "@lsp.type.decorator", "@lsp.type.enumMember", "@lsp.type.macro", "@lsp.type.property", "@lsp.type.typeParameter" }, { fg = p.orange })
  set({ "@lsp.type.function", "@lsp.type.method" }, { fg = p.green })
  set({ "@lsp.type.parameter", "@lsp.type.parameter.typescript", "@lsp.type.parameter.typescriptreact", "@lsp.type.parameter.javascript", "@lsp.type.parameter.javascriptreact", "@lsp.typemod.parameter.declaration.typescript", "@lsp.typemod.parameter.declaration.typescriptreact", "@lsp.typemod.parameter.declaration.javascript", "@lsp.typemod.parameter.declaration.javascriptreact" }, { fg = p.parameter })
  hl("@lsp.type.variable", { fg = p.fg })
  hl("@lsp.mod.readonly", { italic = true })
  hl("@lsp.mod.deprecated", { strikethrough = true })

  hl("DiagnosticError", { fg = p.red })
  hl("DiagnosticWarn", { fg = p.orange })
  hl("DiagnosticInfo", { fg = p.cyan })
  hl("DiagnosticHint", { fg = p.purple })
  hl("DiagnosticOk", { fg = p.green })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = p.red })
  hl("DiagnosticUnderlineWarn", { undercurl = true, sp = p.orange })
  hl("DiagnosticUnderlineInfo", { undercurl = true, sp = p.cyan })
  hl("DiagnosticUnderlineHint", { undercurl = true, sp = p.purple })
  hl("DiagnosticVirtualTextError", { fg = p.red, bg = "#21161a" })
  hl("DiagnosticVirtualTextWarn", { fg = p.orange, bg = "#211a16" })
  hl("DiagnosticVirtualTextInfo", { fg = p.cyan, bg = "#132024" })
  hl("DiagnosticVirtualTextHint", { fg = p.purple, bg = "#1b1824" })

  hl("DiffAdd", { fg = p.green, bg = "#162019" })
  hl("DiffChange", { fg = p.yellow, bg = "#211f16" })
  hl("DiffDelete", { fg = p.red, bg = "#21161a" })
  hl("DiffText", { fg = p.orange, bg = "#2a211a", bold = true })
  hl("GitSignsAdd", { fg = p.green })
  hl("GitSignsChange", { fg = p.orange })
  hl("GitSignsDelete", { fg = p.red })

  hl("SnacksPickerBorder", { fg = p.border, bg = p.bg_float })
  hl("SnacksPickerTitle", { fg = p.yellow, bg = p.bg_float, bold = true })
  hl("SnacksPickerPrompt", { fg = p.yellow, bg = p.bg_float })
  hl("SnacksPickerMatch", { fg = p.yellow, bold = true })
  hl("SnacksPickerDir", { fg = p.comment })
  hl("SnacksPickerFile", { fg = p.fg })
  hl("SnacksPickerSelected", { fg = p.fg, bg = p.surface, bold = true })
  hl("SnacksDashboardHeader", { fg = p.yellow })
  hl("SnacksDashboardKey", { fg = p.red })
  hl("SnacksDashboardDesc", { fg = p.fg_dim })
  hl("SnacksDashboardIcon", { fg = p.cyan })
  hl("SnacksNotifierInfo", { fg = p.cyan })
  hl("SnacksNotifierWarn", { fg = p.orange })
  hl("SnacksNotifierError", { fg = p.red })

  hl("BlinkCmpMenu", { fg = p.fg_dim, bg = p.surface_alt })
  hl("BlinkCmpMenuBorder", { fg = p.border, bg = p.surface_alt })
  hl("BlinkCmpMenuSelection", { fg = p.fg, bg = p.subtle, bold = true })
  hl("BlinkCmpLabel", { fg = p.fg_dim })
  hl("BlinkCmpLabelMatch", { fg = p.yellow, bold = true })
  hl("BlinkCmpKind", { fg = p.purple })
  hl("BlinkCmpDoc", { fg = p.fg_dim, bg = p.bg_float })
  hl("BlinkCmpDocBorder", { fg = p.border, bg = p.bg_float })

  hl("TroubleNormal", { fg = p.fg, bg = p.bg })
  hl("TroubleNormalNC", { fg = p.fg_dim, bg = p.bg })
  hl("TroubleText", { fg = p.fg_dim })
  hl("TroubleCount", { fg = p.surface, bg = p.yellow, bold = true })
  hl("IblIndent", { fg = p.surface_alt })
  hl("IblScope", { fg = p.muted })
  hl("WhichKey", { fg = p.red })
  hl("WhichKeyGroup", { fg = p.cyan })
  hl("WhichKeyDesc", { fg = p.fg_dim })
  hl("WhichKeySeparator", { fg = p.muted })
  hl("WhichKeyFloat", { bg = p.bg_float })
  hl("LazyButton", { fg = p.fg_dim, bg = p.surface })
  hl("LazyButtonActive", { fg = p.surface, bg = p.yellow, bold = true })
  hl("LazyH1", { fg = p.surface, bg = p.yellow, bold = true })
  hl("LazySpecial", { fg = p.cyan })
  hl("MasonHeader", { fg = p.surface, bg = p.yellow, bold = true })
  hl("MasonHighlight", { fg = p.cyan })
  hl("MasonHighlightBlock", { fg = p.surface, bg = p.cyan })
  hl("MasonMuted", { fg = p.comment })
  hl("BufferLineFill", { bg = p.bg })
  hl("BufferLineBackground", { fg = p.comment, bg = p.bg })
  hl("BufferLineBufferSelected", { fg = p.yellow, bg = p.bg, bold = true })
  hl("BufferLineIndicatorSelected", { fg = p.yellow, bg = p.bg })
  hl("BufferLineModified", { fg = p.muted, bg = p.bg })
  hl("BufferLineModifiedSelected", { fg = p.orange, bg = p.bg })

  local terminal = {
    p.surface_alt, p.red, p.green, p.yellow, p.orange, p.purple, p.cyan, p.fg,
    p.subtle, p.red, p.green, p.yellow, p.orange, p.purple, p.cyan, p.fg,
  }
  for i, color in ipairs(terminal) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

return M
